sonar.projectKey=laravel_api
sonar.projectName=Laravel API
sonar.sources=app,routes
sonar.host.url=http://sonarqube:9000
sonar.login=sqp_4633690b736e43893a1a11d9b2cc050d2a62c5a7
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**
