#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

echo "🖌️  Iniciando Pint..."
./vendor/bin/pint
echo "✅ Pint finalizado!"
echo

echo "🧪 Iniciando PHPUnit..."
#./vendor/bin/phpunit
echo "✅ PHPUnit finalizado!"
